config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"

  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
  get '/homes/guest_sign_in', to: 'homes#guest_sign_in'

   devise_for :users, skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admins/sessions"
  }

  get 'search', to: 'searches#search'

  namespace :admins do
    resources :admins, only: [:index, :show, :edit]
    resources :tags, only:[:index, :create, :show, :edit, :update, :destroy]
  end
  namespace :users do
    get 'mypage', to: 'users#mypage'
    get '/users/:id/check', to: 'users#check', as: 'check'
    patch '/users/:id/withdraw', to: 'users#withdraw', as: 'withdraw'
    resources :users, only: [:show, :edit, :update]
  end

  resources :comments, only: [:new, :index, :create, :show, :edit, :update, :destroy] do
    collection do
      get :admin_index
      delete 'admin_destroy/:id', to: 'comments#admin_destroy', as: 'admin_destroy'
    end
  end

  resources :bars, only: [:index, :show, :create] do
     collection do
      get :admin_index
      get 'admin_edit/:id', to: 'bars#admin_edit', as: 'admin_edit'
      delete 'admin_destroy/:id', to: 'bars#admin_destroy', as: 'admin_destroy'
      patch 'admin_update/:id', to: 'bars#admin_update', as: 'admin_update'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :bar

  validates :title, presence: true
  validates :content, presence: true
  validates :bar_id, presence: true
  validates :tag_id, presence: true

  def self.looks(search, word)
    if search == "partial_match"
      @comment = Comment.where("content LIKE?","%#{word}%")
    else
      @comment = Comment.all
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.bar_id = params[:comment][:bar_id]
    if @comment.save
      redirect_to bars_path, notice: "コメントが投稿されました"
    else
      flash.now[:alert] = "コメントの投稿に失敗しました"
      render :new
    end
  end

  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
    @user = @comment.user
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to bars_path
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to comment_path
  end

def admin_index
  @comments = Comment.all
  @users = User.all
end

def admin_destroy
  comment = Comment.find(params[:id])
  comment.destroy
  redirect_to admin_index_comments_path
end

  private

  def comment_params
    params.require(:comment).permit(:bar_id, :tag_id, :title, :content, :star)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/admin_index.html.erb
<div class="container mt-5">
<h3>レビューコメント一覧</h3>
<table class="table mt-3">
  <tr>
    <th>名前</th>
    <th>コメント</th>
    <th>bar名</th>
    <th>評価</th>
    <th>投稿日</th>
    <th></th>
  </tr>
<% @comments.each do |comment| %>
  <tr>
    <td><%= @users.find(comment.user_id).name %></td>
    <td><%= comment.content %></td>
    <td><%= comment.bar.name %></td>
    <td>
      <div id="show_star-<%= comment.id %>"></div>
        <script>
          var elem = document.querySelector('#show_star-<%= comment.id %>');
          var opt = {
            starOff   : '<%= asset_path('star-off.png') %>',
            starOn    : '<%= asset_path('star-on.png') %>',
            half      : '<%= asset_path('star-half.png') %>',
            readOnly  : true,
            score     : <%= comment.star %>
          };
          raty(elem,opt);
        </script>
    </td>
    <td>
      <%= comment.created_at.strftime('%Y/%m/%d') %>
      </td>
    <td>
      <%= link_to '削除', admin_destroy_comments_path(comment), method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-sm btn-danger" %>
    </td>
  </tr>
<% end %>
</table>

</div>

app/views/comments/edit.html.erb
<%= form_with model: @comment do |f| %>
  <label for="inputTitle">タイトル</label>
    <%= f.text_field :title, autofocus: true, id:"inputTitle", placeholder:"タイトル"%>
  <label for="inputContent">コメント</label>
    <%= f.text_field :content, autofocus: true, id:"inputContent", placeholder:"コメント"%>
 <label for="inputStar">評価</label>
    <%= f.select :star, options_for_select([1, 2, 3, 4, 5]), prompt: "評価を選択してください" %>
  <%= f.submit "変更を保存" %>
<% end %>

app/views/comments/index.html.erb
<% @comments.each do |comment| %>
  <div>
    <p>タイトル：<%= link_to comment.title, comment_path(comment) %></p>
    <p>ユーザーネーム：<%= comment.user.name %></p>
    <p>BAR名：<%= comment.bar.name %></p>
   <p>投稿日：<%= comment.created_at.strftime('%Y/%m/%d') %></p>
  </div>
<% end %>

app/views/comments/new.html.erb
<h1>投稿フォーム</h1>
<%= form_with model: @comment do |f| %>
  <h4>bar名</h4>
    <%= f.collection_select :bar_id, Bar.all, :id, :name, include_blank: "選択して下さい", required: true %>
  <h4>タグ</h4>
    <%= f.collection_select :tag_id, Tag.all, :id, :name, include_blank: "選択して下さい", required: true %>
  <h4>タイトル</h4>
    <%= f.text_field :title, required: true %>
  <h4>内容</h4>
    <%= f.text_area :content, required: true %>
    <%= f.submit '投稿',class:"btn btn-success" %>
  <div class="form-group row" id="star">
    <%= f.label :star,'評価 ', class:'col-md-3 col-form-label' %>
    <%= f.hidden_field :star, id: :review_star %>
　</div>
  <div class="form-group position-static">
    <div id="post_raty"></div>
      <script>
          var elem = document.querySelector('#post_raty');
          var opt = {
            starOff   : '<%= asset_path('star-off.png') %>',
            starOn    : '<%= asset_path('star-on.png') %>',
            readOnly  : false,
            scoreName: 'comment[star]'
          };
          raty(elem,opt);
      </script>
  </div>
<% end %>
<%= link_to "戻る", bars_path %>

app/views/comments/show.html.erb
<div>
  <h1><%= @comment.bar.name %></h1>
  <h3><%= @comment.bar.address %></h3>
  <p>タイトル:<%= @comment.title %></p>
  <p>コメント:<%= @comment.content %></p>

  <p>評価 :<%= @comment.star%>点</p>
    <div id="show_star-<%= @comment.id %>"></div>
    <script>
      var elem = document.querySelector('#show_star-<%= @comment.id %>');
      var opt = {
        starOff   : '<%= asset_path('star-off.png') %>',
        starOn    : '<%= asset_path('star-on.png') %>',
        half      : '<%= asset_path('star-half.png') %>',
        readOnly  : true,
        score     : <%= @comment.star %>
        };
      raty(elem,opt);
    </script>
    </div>
    <% if @user == current_user %>
       <%= link_to "削除する", comment_path(@comment), method: :delete,class:"btn btn-sm btn-danger" %>
       <%= link_to '編集する', edit_comment_path, class:"btn btn-sm btn-success" %>
    <% end %>
  <p>投稿日：<%= @comment.created_at.strftime('%Y/%m/%d') %></p>
</div>