config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"

  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
  get '/homes/guest_sign_in', to: 'homes#guest_sign_in'

   devise_for :users, skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admins/sessions"
  }

  get 'search', to: 'searches#search'

  namespace :admins do
    resources :admins, only: [:index, :show, :edit]
    resources :tags, only:[:index, :create, :show, :edit, :update, :destroy]
  end
  namespace :users do
    get 'mypage', to: 'users#mypage'
    get '/users/:id/check', to: 'users#check', as: 'check'
    patch '/users/:id/withdraw', to: 'users#withdraw', as: 'withdraw'
    resources :users, only: [:show, :edit, :update]
  end

  resources :comments, only: [:new, :index, :create, :show, :edit, :update, :destroy] do
    collection do
      get :admin_index
      delete 'admin_destroy/:id', to: 'comments#admin_destroy', as: 'admin_destroy'
    end
  end

  resources :bars, only: [:index, :show, :create] do
     collection do
      get :admin_index
      get 'admin_edit/:id', to: 'bars#admin_edit', as: 'admin_edit'
      delete 'admin_destroy/:id', to: 'bars#admin_destroy', as: 'admin_destroy'
      patch 'admin_update/:id', to: 'bars#admin_update', as: 'admin_update'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bar.rb
class Bar < ApplicationRecord

  has_many :comments, dependent: :destroy
  has_many :bar_tags, dependent: :destroy
  has_many :tags, through: :bar_tags

  validates :name, presence: true
  validates :address, presence: true

  def self.looks(search, word)
    if search == "partial_match"
      @bar = Bar.where("name LIKE ?", "%#{word}%")
    else
      @bar = Bar.all
    end
  end

end

app/controllers/bars_controller.rb
class BarsController < ApplicationController

  def index
    @bars = Bar.all.page(params[:page])
    if params[:word].present?
      bar_results = Bar.where("name LIKE ?", "%#{params[:search]}%")
      comment_results = Comment.where("content LIKE ?", "%#{params[:search]}%")
      tag_results = Tag.where("name LIKE ?", "%#{params[:search]}%")
      @results = bar_results + comment_results + tag_results
    else
      @results = []
    end
  end

  def show
    @bar = Bar.find(params[:id])
    @comments = @bar.comments
  end

  def admin_index
    @bar = Bar.new
    @bars = Bar.all
  end

  def create
    @bar = Bar.new(bar_params)
    if @bar.save
    bar_tag = BarTag.new(bar_id: @bar.id, tag_id: params[:bar][:tag_id])
    bar_tag.save
    redirect_to admin_index_bars_path
    else
      @bars = Bar.all
      render :admin_index
    end
  end

  def admin_destroy
    bar = Bar.find(params[:id])
    bar.destroy
    redirect_to admin_index_bars_path
  end

  def admin_edit
   @bar = Bar.find(params[:id])
  end

  def admin_update
    @bar = Bar.find(params[:id])
    @bar.update(bar_params)
    redirect_to admin_index_bars_path
  end

  private

  def bar_params
    params.require(:bar).permit(:name,:address)
  end

end

app/views/bars/admin_edit.html.erb
<h1>編集画面</h1>

<%= form_with model: @bar, url: admin_update_bars_path do |form| %>

  <h4>bar名</h4>
  <%= form.text_field :name %>

  <h4>住所</h4>
  <%= form.text_field :address %>

  <%= form.submit '保存' %>

<% end %>

app/views/bars/admin_index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <h1>管理者用Bar一覧</h1>
        <div class="col-md-10">
          <h3>投稿フォーム</h3>
            <div class="row gy-2 gx-3 align-items-center">
              <%= form_with model: @bar do |f| %>
                <label class="control-label">
                  bar名
                  <%= f.text_field :name %>
                </label>
                <label class="control-label">
                  住所
                  <%= f.text_field :address %>
                </label>
                <label class="control-label">
                  タグ
                  <%= f.collection_select :tag_id, Tag.all, :id, :name, include_blank: "選択して下さい" %>
                </label>
                <%= f.submit "投稿", class: "btn btn-primary" %>
              <% end %>
            </div>
        </div>
        <table class="table">
          <tbody>
            <tr>
              <th>bar名</th>
              <th>タグ</th>
            </tr>
          <% @bars.each do |bar| %>
            <tr>
              <td>
                <%= bar.name %>
              </td>
              <td>
                <%= bar.tags.pluck(:name).join("") %>
              </td>
              <td>
                <%= link_to "Edit", admin_edit_bars_path(bar.id), class:"btn btn-sm btn-success" %>
              </td>
              <td>
                <%= link_to "Destroy", admin_destroy_bars_path(bar), method: :delete,"data-confirm" => "本当に削しますか？",class:"btn btn-sm btn-danger" %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/bars/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <div class="d-flex justify-content-between align-items-center">
        <h1>Bar一覧</h1>
        <div class="col-md-10">
          <div class="search_form mb-4">
            <%= form_with url: search_path, local: true, method: :get, class: "form-inline" do |f| %>
              <div class="form-group">
                <%= f.text_field :word, class: "form-control", placeholder: "検索するキーワードを入力してください" %>
              </div>
              <div class="form-group">
                <%= f.select :range, options_for_select([['Comment'], ['Bar'], ['Tag']]), class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.select :search, options_for_select([["部分一致","partial_match"]]), class: "form-control" %>
              </div>
                <%= f.submit "検索", class: "btn btn-primary" %>
            <% end %>
            <p>
              <%= link_to '投稿ページ', new_comment_path, class: "btn btn-secondary"  %>
            </p>
          </div>
        </div>
      </div>
      <table class="table">
        <tbody>
          <tr>
            <th>BAR名</th>
            <th>タグ</th>
          </tr>
        <% @bars.each do |bar| %>
          <tr>
            <td>
              <%= link_to bar.name, bar_path(bar.id) %>
            </td>
            <td>
              <%= bar.tags.pluck(:name).join("") %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <div class="col-md-12 d-flex justify-content-end align-self-end">
        <%= paginate @bars %>
      </div>
    </div>
  </div>
</div>

app/views/bars/show.html.erb
<div>
  <h1>BAR名：<%= @bar.name %></h1>
  <h3>住所 : <%= @bar.address %></h3>
</div>
  <table class="table">
    <tbody>
      <tr>
        <th>投稿日</th>
        <th>ユーザー名</th>
        <th>タイトル</th>
        <th>コメント</th>
        <th>評価</th>
      </tr>
      <% @comments.each do |comment| %>
        <tr>
          <td>
            <%= comment.created_at.strftime('%Y/%m/%d') %>
          </td>
          <td>
            <% if current_user && current_user.id == comment.user.id %>
              <%= link_to comment.user.name, users_mypage_path(comment.user) %>
            <% else %>
              <%= link_to comment.user.name,  users_user_path(comment.user) %>
            <% end %>
          </td>
          <td>
            <%= link_to comment.title, comment_path(comment.id) %>
          </td>
          <td>
            <%= comment.content %>
          </td>
          <td>
             <div id="show_star-<%= comment.id %>"></div>
            <script>
              var elem = document.querySelector('#show_star-<%= comment.id %>');
              var opt = {
                starOff   : '<%= asset_path('star-off.png') %>',
                starOn    : '<%= asset_path('star-on.png') %>',
                half      : '<%= asset_path('star-half.png') %>',
                readOnly  : true,
                score     : <%= comment.star %>
                };
                raty(elem,opt);
            </script>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to "戻る", bars_path %>