config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"

  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
  get '/homes/guest_sign_in', to: 'homes#guest_sign_in'

   devise_for :users, skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admins/sessions"
  }

  get 'search', to: 'searches#search'

  namespace :admins do
    resources :admins, only: [:index, :show, :edit]
    resources :tags, only:[:index, :create, :show, :edit, :update, :destroy]
  end
  namespace :users do
    get 'mypage', to: 'users#mypage'
    get '/users/:id/check', to: 'users#check', as: 'check'
    patch '/users/:id/withdraw', to: 'users#withdraw', as: 'withdraw'
    resources :users, only: [:show, :edit, :update]
  end

  resources :comments, only: [:new, :index, :create, :show, :edit, :update, :destroy] do
    collection do
      get :admin_index
      delete 'admin_destroy/:id', to: 'comments#admin_destroy', as: 'admin_destroy'
    end
  end

  resources :bars, only: [:index, :show, :create] do
     collection do
      get :admin_index
      get 'admin_edit/:id', to: 'bars#admin_edit', as: 'admin_edit'
      delete 'admin_destroy/:id', to: 'bars#admin_destroy', as: 'admin_destroy'
      patch 'admin_update/:id', to: 'bars#admin_update', as: 'admin_update'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :bar_tags, dependent: :destroy
  has_many :bars, through: :bar_tags

  validates :name, presence: true, uniqueness: true

  def self.looks(search, word)
    if search == "partial_match"
      @tag = Tag.where("name LIKE ?", "%#{word}%")
    else
      @tag = Tag.all
    end
  end
end

app/controllers/admins/tags_controller.rb
class Admins::TagsController < ApplicationController

  def index
    @tag = Tag.new
    @tags = Tag.all
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to admins_tags_path, notice: "タグが作成されました"
    else
      flash.now[:alert] = "タグの作成に失敗しました"
      @tags = Tag.all
      render :index
    end
  end

  def show

  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    @tag.update(tag_params)
    redirect_to admins_tags_path
  end

  def destroy
    tag = Tag.find(params[:id])
    tag.destroy
    redirect_to admins_tags_path
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/admins/tags/edit.html.erb
<h2>タグ名編集</h2>
<%= form_with model: [:admins, @tag] do |f| %>
  <label for="inputName">Tag</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"タグ名"%>
  <%= f.submit "変更を保存", class: "btn btn-primary" %>
<% end %>

app/views/admins/tags/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <h1>タグ一覧</h1>
        <%= form_with model: [:admins, @tag] do |f| %>
          <h4>タグ名</h4>
          <%= f.text_field :name %>
          <%= f.submit '投稿', class: "btn btn-primary" %>
        <% end %>
        <table class="table">
          <tbody>
            <% @tags.each do |tag| %>
              <tr>
                <td>
                  <%= tag.name %>
                </td>
                <td>
                  <%= link_to "編集する", edit_admins_tag_path(tag.id), class:"btn btn-sm btn-success" %>
                </td>
                <td>
                  <%= link_to "削除する", admins_tag_path(tag), method: :delete,"data-confirm" => "本当に削しますか？",class:"btn btn-sm btn-danger" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>