config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"

  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
  get '/homes/guest_sign_in', to: 'homes#guest_sign_in'

   devise_for :users, skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admins/sessions"
  }

  get 'search', to: 'searches#search'

  namespace :admins do
    resources :admins, only: [:index, :show, :edit]
    resources :tags, only:[:index, :create, :show, :edit, :update, :destroy]
  end
  namespace :users do
    get 'mypage', to: 'users#mypage'
    get '/users/:id/check', to: 'users#check', as: 'check'
    patch '/users/:id/withdraw', to: 'users#withdraw', as: 'withdraw'
    resources :users, only: [:show, :edit, :update]
  end

  resources :comments, only: [:new, :index, :create, :show, :edit, :update, :destroy] do
    collection do
      get :admin_index
      delete 'admin_destroy/:id', to: 'comments#admin_destroy', as: 'admin_destroy'
    end
  end

  resources :bars, only: [:index, :show, :create] do
     collection do
      get :admin_index
      get 'admin_edit/:id', to: 'bars#admin_edit', as: 'admin_edit'
      delete 'admin_destroy/:id', to: 'bars#admin_destroy', as: 'admin_destroy'
      patch 'admin_update/:id', to: 'bars#admin_update', as: 'admin_update'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bar.rb
class Bar < ApplicationRecord

  has_many :comments, dependent: :destroy
  has_many :bar_tags, dependent: :destroy
  has_many :tags, through: :bar_tags

  validates :name, presence: true
  validates :address, presence: true

  def self.looks(search, word)
    if search == "partial_match"
      @bar = Bar.where("name LIKE ?", "%#{word}%")
    else
      @bar = Bar.all
    end
  end

end

app/models/bar_tag.rb
class BarTag < ApplicationRecord

  belongs_to :bar
  belongs_to :tag

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :bar

  validates :title, presence: true
  validates :content, presence: true
  validates :bar_id, presence: true
  validates :tag_id, presence: true

  def self.looks(search, word)
    if search == "partial_match"
      @comment = Comment.where("content LIKE?","%#{word}%")
    else
      @comment = Comment.all
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :bar_tags, dependent: :destroy
  has_many :bars, through: :bar_tags

  validates :name, presence: true, uniqueness: true

  def self.looks(search, word)
    if search == "partial_match"
      @tag = Tag.where("name LIKE ?", "%#{word}%")
    else
      @tag = Tag.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :comments, dependent: :destroy
         def active_for_authentication?
            super && (is_deleted == false)
         end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/bars_controller.rb
class BarsController < ApplicationController

  def index
    @bars = Bar.all.page(params[:page])
    if params[:word].present?
      bar_results = Bar.where("name LIKE ?", "%#{params[:search]}%")
      comment_results = Comment.where("content LIKE ?", "%#{params[:search]}%")
      tag_results = Tag.where("name LIKE ?", "%#{params[:search]}%")
      @results = bar_results + comment_results + tag_results
    else
      @results = []
    end
  end

  def show
    @bar = Bar.find(params[:id])
    @comments = @bar.comments
  end

  def admin_index
    @bar = Bar.new
    @bars = Bar.all
  end

  def create
    @bar = Bar.new(bar_params)
    if @bar.save
    bar_tag = BarTag.new(bar_id: @bar.id, tag_id: params[:bar][:tag_id])
    bar_tag.save
    redirect_to admin_index_bars_path
    else
      @bars = Bar.all
      render :admin_index
    end
  end

  def admin_destroy
    bar = Bar.find(params[:id])
    bar.destroy
    redirect_to admin_index_bars_path
  end

  def admin_edit
   @bar = Bar.find(params[:id])
  end

  def admin_update
    @bar = Bar.find(params[:id])
    @bar.update(bar_params)
    redirect_to admin_index_bars_path
  end

  private

  def bar_params
    params.require(:bar).permit(:name,:address)
  end

end

app/controllers/bars_coplacntroller.rb
class BarsController < ApplicationController

  def new

  end

  def index

  end

  def show

  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.bar_id = params[:comment][:bar_id]
    if @comment.save
      redirect_to bars_path, notice: "コメントが投稿されました"
    else
      flash.now[:alert] = "コメントの投稿に失敗しました"
      render :new
    end
  end

  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
    @user = @comment.user
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to bars_path
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to comment_path
  end

def admin_index
  @comments = Comment.all
  @users = User.all
end

def admin_destroy
  comment = Comment.find(params[:id])
  comment.destroy
  redirect_to admin_index_comments_path
end

  private

  def comment_params
    params.require(:comment).permit(:bar_id, :tag_id, :title, :content, :star)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end

  def guest_sign_in
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
    sign_in user
    redirect_to users_mypage_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def new

  end

  def index

  end

  def show

  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  #before_action :authenticate_user!
  def search
    @range = params[:range]
    @word = params[:word]
    if @range == "Comment"
      @comments = Comment.looks(params[:search], params[:word])
    elsif @range == "Tag"
      @tags = Tag.looks(params[:search], params[:word])
    else
      @bars = Bar.looks(params[:search], params[:word])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/admins/admins/index.html.erb
<h1>ユーザー一覧</h1>

<table class="table">

  <tr>
    <th>ID</th>
    <th>名前</th>
    <th>メールアドレス</th>
    <th>退会ステータス</th>
  </tr>

  <% @users.each do |user| %>

    <tr>
      <td>
        <%= user.id %>
      </td>
      <td>
        <%= user.name %>
      </td>
      <td>
        <%= user.email %>
      </td>
      <td>
        <%= user.is_deleted ? "退会済み" : "会員" %>
      </td>
    </tr>

  <% end %>

</table>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BarTime</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/ab9a69a7da.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bar Time</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            <div class="navbar-collapse collapse show " id="navbarNavDropdown"style>
              <ul class="navbar-nav ml-auto">
                <% if user_signed_in? %>
                  <li class="nav-link text-light">
                    <%= link_to 'マイページ',  users_mypage_path,class:"text-light" %>
                  </li>
                  <li class="nav-link text-light">
                    <%= link_to "Bar一覧", bars_path,class:"text-light" %>
                  </li>
                  <li class="nav-link text-light">
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class:"text-light" %>
                  </li>
                  <li class="nav-link text-light">
                    <%= link_to "退会ページ", users_check_path(current_user.id),class:"text-light" %>
                  </li>
                <% elsif admin_signed_in? %>
      　          <li class="nav-link text-light">
                    <%= link_to "ログアウト", destroy_admin_session_path, method: :delete,class:"text-light" %>
                  </li>
                  <li class="nav-link text-light">
                    <%= link_to "ユーザ一覧", admins_admins_path,class:"text-light" %>
                  </li>
                  <li class="nav-link text-light">
                    <%= link_to "タグ一覧", admins_tags_path,class:"text-light" %>
                  </li>
                  <li class="nav-link text-light">
                    <%= link_to "Bar一覧", admin_index_bars_path,class:"text-light" %>
                  </li>
                  <li class="nav-link text-light">
                    <%= link_to "レビュー一覧", admin_index_comments_path,class:"text-light" %>
                  </li>
                <% else %>
                  <li class="nav-link text-light">
                    <%= link_to "新規登録", new_user_registration_path,class:"text-light" %>
                  </li>
                  <li class="nav-link text-light">
                    <%= link_to "ログイン", new_user_session_path,class:"text-light" %>
                  </li>
                  <li class="nav-link text-light">
                    <%= link_to "ゲストログイン（閲覧用）", homes_guest_sign_in_path, method: :post,class:"text-light" %>
                  </li>
                  <li class="nav-link text-light">
                    <%= link_to "管理者ログイン", new_admin_session_path,class:"text-light" %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
    </header>
    <%= yield %>
  </body>
</html>